//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGL_KP_M_Account_Group_H
    {
        public CGL_KP_M_Account_Group_H()
        {
            this.CGL_KP_M_Account_H = new HashSet<CGL_KP_M_Account_H>();
        }
    
        public int Account_Group_Id { get; set; }
        public string Account_Group_Name { get; set; }
        public string Account_Group_Type { get; set; }
        public string Description { get; set; }
        public bool Is_Deleted { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    
        public virtual ICollection<CGL_KP_M_Account_H> CGL_KP_M_Account_H { get; set; }
    }
}
