//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGL_KP_R_Journal_H
    {
        public CGL_KP_R_Journal_H()
        {
            this.CGL_KP_R_Journal_D = new HashSet<CGL_KP_R_Journal_D>();
        }
    
        public int Journal_Id { get; set; }
        public string Journal_No { get; set; }
        public System.DateTime Journal_Date { get; set; }
        public int Legal_Entity_Id { get; set; }
        public Nullable<int> Journal_Ref_Id { get; set; }
        public Nullable<int> Transaction_Type_Id { get; set; }
        public Nullable<int> Reference_Id { get; set; }
        public string Description { get; set; }
        public bool Is_Deleted { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    
        public virtual CGL_KP_M_Legal_Entity_H CGL_KP_M_Legal_Entity_H { get; set; }
        public virtual ICollection<CGL_KP_R_Journal_D> CGL_KP_R_Journal_D { get; set; }
    }
}
