//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGL_KP_M_Revenue_Type_H
    {
        public CGL_KP_M_Revenue_Type_H()
        {
            this.CGL_KP_R_Revenue_H = new HashSet<CGL_KP_R_Revenue_H>();
        }
    
        public int Revenue_Type_Id { get; set; }
        public string Revenue_Type_Code { get; set; }
        public string Revenue_Type_Description { get; set; }
        public int Account_Id { get; set; }
        public bool Need_Member { get; set; }
        public bool Need_Approval { get; set; }
        public bool Is_Deleted { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    
        public virtual CGL_KP_M_Account_H CGL_KP_M_Account_H { get; set; }
        public virtual ICollection<CGL_KP_R_Revenue_H> CGL_KP_R_Revenue_H { get; set; }
    }
}
