//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGL_KP_M_Legal_Entity_H
    {
        public CGL_KP_M_Legal_Entity_H()
        {
            this.CGL_KP_M_Period_H = new HashSet<CGL_KP_M_Period_H>();
            this.CGL_KP_M_Member_H = new HashSet<CGL_KP_M_Member_H>();
            this.CGL_KP_R_Cooperative_Balance_H = new HashSet<CGL_KP_R_Cooperative_Balance_H>();
            this.CGL_KP_R_Cooperative_Beginning_Balance_H = new HashSet<CGL_KP_R_Cooperative_Beginning_Balance_H>();
            this.CGL_KP_R_Journal_H = new HashSet<CGL_KP_R_Journal_H>();
        }
    
        public int Legal_Entity_Id { get; set; }
        public string Legal_Entity_Code { get; set; }
        public string Legal_Entity_Name { get; set; }
        public bool Is_Deleted { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    
        public virtual ICollection<CGL_KP_M_Period_H> CGL_KP_M_Period_H { get; set; }
        public virtual ICollection<CGL_KP_M_Member_H> CGL_KP_M_Member_H { get; set; }
        public virtual ICollection<CGL_KP_R_Cooperative_Balance_H> CGL_KP_R_Cooperative_Balance_H { get; set; }
        public virtual ICollection<CGL_KP_R_Cooperative_Beginning_Balance_H> CGL_KP_R_Cooperative_Beginning_Balance_H { get; set; }
        public virtual ICollection<CGL_KP_R_Journal_H> CGL_KP_R_Journal_H { get; set; }
    }
}
