//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGL_KP_M_Form_Master_H
    {
        public CGL_KP_M_Form_Master_H()
        {
            this.CGL_KP_M_Assignment_H = new HashSet<CGL_KP_M_Assignment_H>();
        }
    
        public int Form_ID { get; set; }
        public string Form_Name { get; set; }
        public string Uri { get; set; }
        public int Form_Type_Id { get; set; }
        public string Img_Uri { get; set; }
        public bool Is_Deleted { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
    
        public virtual ICollection<CGL_KP_M_Assignment_H> CGL_KP_M_Assignment_H { get; set; }
        public virtual CGL_KP_M_Form_Type_H CGL_KP_M_Form_Type_H { get; set; }
    }
}
