//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRR_M_User_Login_H
    {
        public int Id { get; set; }
        public string User_Name { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public bool Status { get; set; }
    }
}
