//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRR_KK_M_Screen_Master_H
    {
        public int Screen_Id { get; set; }
        public string Screen_Name { get; set; }
        public string Screen_URI { get; set; }
        public string Screen_Image { get; set; }
    }
}
