//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class srr_devEntities : DbContext
    {
        public srr_devEntities()
            : base("name=srr_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SRR_M_User_Login_H> SRR_M_User_Login_H { get; set; }
        public DbSet<SRR_KK_M_Screen_Master_H> SRR_KK_M_Screen_Master_H { get; set; }
    }
}
