//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR_Devolopment.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class srr_devEntities : DbContext
    {
        public srr_devEntities()
            : base("name=srr_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CGL_KP_M_Legal_Entity_H> CGL_KP_M_Legal_Entity_H { get; set; }
        public DbSet<CGL_KP_M_Period_H> CGL_KP_M_Period_H { get; set; }
        public DbSet<CGL_KP_M_Period_Status_H> CGL_KP_M_Period_Status_H { get; set; }
        public DbSet<CGL_KP_M_Status_H> CGL_KP_M_Status_H { get; set; }
        public DbSet<CGL_KP_M_Member_H> CGL_KP_M_Member_H { get; set; }
        public DbSet<CGL_KP_M_AccessRights_H> CGL_KP_M_AccessRights_H { get; set; }
        public DbSet<CGL_KP_M_Assignment_H> CGL_KP_M_Assignment_H { get; set; }
        public DbSet<CGL_KP_M_Form_Master_H> CGL_KP_M_Form_Master_H { get; set; }
        public DbSet<CGL_KP_M_Form_Type_H> CGL_KP_M_Form_Type_H { get; set; }
        public DbSet<CGL_KP_M_Group_H> CGL_KP_M_Group_H { get; set; }
        public DbSet<CGL_KP_M_UserProfile_H> CGL_KP_M_UserProfile_H { get; set; }
        public DbSet<CGL_KP_M_Account_Group_H> CGL_KP_M_Account_Group_H { get; set; }
        public DbSet<CGL_KP_M_Account_H> CGL_KP_M_Account_H { get; set; }
        public DbSet<CGL_KP_M_Expenditure_Type_H> CGL_KP_M_Expenditure_Type_H { get; set; }
        public DbSet<CGL_KP_M_Revenue_Type_H> CGL_KP_M_Revenue_Type_H { get; set; }
        public DbSet<CGL_KP_R_Expenditure_H> CGL_KP_R_Expenditure_H { get; set; }
        public DbSet<CGL_KP_R_Journal_D> CGL_KP_R_Journal_D { get; set; }
        public DbSet<CGL_KP_R_Journal_H> CGL_KP_R_Journal_H { get; set; }
        public DbSet<CGL_KP_R_Member_Balance_H> CGL_KP_R_Member_Balance_H { get; set; }
        public DbSet<CGL_KP_R_Member_Beginning_Balance_H> CGL_KP_R_Member_Beginning_Balance_H { get; set; }
        public DbSet<CGL_KP_R_Member_Loan_H> CGL_KP_R_Member_Loan_H { get; set; }
        public DbSet<CGL_KP_S_Setting_H> CGL_KP_S_Setting_H { get; set; }
        public DbSet<CGL_KP_S_Transaction_Type_H> CGL_KP_S_Transaction_Type_H { get; set; }
        public DbSet<CGL_KP_R_Cooperative_Balance_H> CGL_KP_R_Cooperative_Balance_H { get; set; }
        public DbSet<CGL_KP_R_Cooperative_Beginning_Balance_H> CGL_KP_R_Cooperative_Beginning_Balance_H { get; set; }
        public DbSet<CGL_KP_M_UserProfile_D> CGL_KP_M_UserProfile_D { get; set; }
        public DbSet<CGL_KP_R_Revenue_H> CGL_KP_R_Revenue_H { get; set; }
    
        public virtual ObjectResult<USP_CG_KP_M_AccessRights_H_Find_Result> USP_CG_KP_M_AccessRights_H_Find(Nullable<int> groupID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CG_KP_M_AccessRights_H_Find_Result>("USP_CG_KP_M_AccessRights_H_Find", groupIDParameter);
        }
    
        public virtual ObjectResult<USP_CG_KP_M_Form_Type_H_Find_Result> USP_CG_KP_M_Form_Type_H_Find(Nullable<int> groupID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CG_KP_M_Form_Type_H_Find_Result>("USP_CG_KP_M_Form_Type_H_Find", groupIDParameter);
        }
    
        public virtual ObjectResult<USP_CG_KP_M_FormMaster_H_Find_R_Result> USP_CG_KP_M_FormMaster_H_Find_R(Nullable<int> groupID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CG_KP_M_FormMaster_H_Find_R_Result>("USP_CG_KP_M_FormMaster_H_Find_R", groupIDParameter);
        }
    
        public virtual ObjectResult<USP_CG_KP_M_UserProfile_H_Find_Result> USP_CG_KP_M_UserProfile_H_Find(string userID, string password)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CG_KP_M_UserProfile_H_Find_Result>("USP_CG_KP_M_UserProfile_H_Find", userIDParameter, passwordParameter);
        }
    
        public virtual ObjectResult<USP_CGL_KP_M_Member_H_Find_Result> USP_CGL_KP_M_Member_H_Find(string name, Nullable<int> legalEntityID)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var legalEntityIDParameter = legalEntityID.HasValue ?
                new ObjectParameter("LegalEntityID", legalEntityID) :
                new ObjectParameter("LegalEntityID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CGL_KP_M_Member_H_Find_Result>("USP_CGL_KP_M_Member_H_Find", nameParameter, legalEntityIDParameter);
        }
    
        public virtual ObjectResult<USP_CGL_KP_R_Revenue_H_Find_Result> USP_CGL_KP_R_Revenue_H_Find(Nullable<int> legalEntityID, Nullable<int> period_Id)
        {
            var legalEntityIDParameter = legalEntityID.HasValue ?
                new ObjectParameter("LegalEntityID", legalEntityID) :
                new ObjectParameter("LegalEntityID", typeof(int));
    
            var period_IdParameter = period_Id.HasValue ?
                new ObjectParameter("Period_Id", period_Id) :
                new ObjectParameter("Period_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CGL_KP_R_Revenue_H_Find_Result>("USP_CGL_KP_R_Revenue_H_Find", legalEntityIDParameter, period_IdParameter);
        }
    
        public virtual int USP_CGL_KP_R_Generate_Simpanan_Pokok(Nullable<int> member_Id, Nullable<System.DateTime> transaction_Date, ObjectParameter success, ObjectParameter message)
        {
            var member_IdParameter = member_Id.HasValue ?
                new ObjectParameter("Member_Id", member_Id) :
                new ObjectParameter("Member_Id", typeof(int));
    
            var transaction_DateParameter = transaction_Date.HasValue ?
                new ObjectParameter("Transaction_Date", transaction_Date) :
                new ObjectParameter("Transaction_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CGL_KP_R_Generate_Simpanan_Pokok", member_IdParameter, transaction_DateParameter, success, message);
        }
    
        public virtual int USP_CGL_KP_R_Generate_Simpanan_Wajib(Nullable<System.DateTime> transaction_Date, ObjectParameter success, ObjectParameter message)
        {
            var transaction_DateParameter = transaction_Date.HasValue ?
                new ObjectParameter("Transaction_Date", transaction_Date) :
                new ObjectParameter("Transaction_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CGL_KP_R_Generate_Simpanan_Wajib", transaction_DateParameter, success, message);
        }
    
        public virtual int USP_CGL_KP_T_Generate_Transaction_Number_For_Auto(string transaction_Type_Code, Nullable<System.DateTime> transaction_Date, ObjectParameter transaction_No)
        {
            var transaction_Type_CodeParameter = transaction_Type_Code != null ?
                new ObjectParameter("Transaction_Type_Code", transaction_Type_Code) :
                new ObjectParameter("Transaction_Type_Code", typeof(string));
    
            var transaction_DateParameter = transaction_Date.HasValue ?
                new ObjectParameter("Transaction_Date", transaction_Date) :
                new ObjectParameter("Transaction_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CGL_KP_T_Generate_Transaction_Number_For_Auto", transaction_Type_CodeParameter, transaction_DateParameter, transaction_No);
        }
    
        public virtual ObjectResult<USP_CGL_KP_T_Generate_Transaction_Number_Result> USP_CGL_KP_T_Generate_Transaction_Number(string transaction_Type_Code, Nullable<System.DateTime> transaction_Date)
        {
            var transaction_Type_CodeParameter = transaction_Type_Code != null ?
                new ObjectParameter("Transaction_Type_Code", transaction_Type_Code) :
                new ObjectParameter("Transaction_Type_Code", typeof(string));
    
            var transaction_DateParameter = transaction_Date.HasValue ?
                new ObjectParameter("Transaction_Date", transaction_Date) :
                new ObjectParameter("Transaction_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CGL_KP_T_Generate_Transaction_Number_Result>("USP_CGL_KP_T_Generate_Transaction_Number", transaction_Type_CodeParameter, transaction_DateParameter);
        }
    
        public virtual ObjectResult<USP_CGL_KP_R_Member_Loan_H_Find_Result> USP_CGL_KP_R_Member_Loan_H_Find(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CGL_KP_R_Member_Loan_H_Find_Result>("USP_CGL_KP_R_Member_Loan_H_Find", memberIDParameter);
        }
    }
}
